### ISSUE TITLE
nfrrecs's mod entry

### ISSUE THREAD

**Issue by nfrrecs** [user95401/Ryzen-Mods#14]
[mod]

; name of target file in release
file = nfrrecs.mod.dll

; repository
repo = nfrrecs/mod

; u can set exact version if it really needs
release_tag = latest

; small description about ur mod
desc = <cr>panini is ever</c> got <cg>fly away</c>?

**Comment by nfrrecs** [comment]
!setlabels shit,no-panini,spam,asd

**Comment by user95401** [comment]
!setlabels shit,no-panini,spam,asd

**Comment by nfrrecs** [comment]
haha u cant :D

**Comment by nfrrecs** [comment]
!setlabels shit,no-panini,spam,asd
